on:
  push:
    branches: 
      - "test-workflow"
    tags:
      - "v*.*.*"
    #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') #TODO check the format is X.Y.Z and they are number
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: npm install, build, and test backend #TODO if the user put "backend" in the commit description only?
      run: |
        cd ./backend
        npm install
        npm audit fix
        npm run build --if-present
        npm run test --if-present

    - name: npm install, build, and test frontend #TODO if the user put backend in the commit description only? TODO async?
      run: |
        cd ./frontend
        npm install
        npm audit fix
        npm run build --if-present
        npm run test --if-present

    #- name: Audit
    #  run: ping -n 1 127.0.0.1 #TODO

    #- name: Linting
    #  run: ping -n 1 127.0.0.1 #TODO

    #- name: Unit Testing
    #  run: ping -n 1 127.0.0.1 #TODO 

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #uses: docker/login-action@v2
      #with:
      #  username: ${{ secrets.DOCKER_USERNAME }}
      #  password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag todo-app:latest #TODO : date +%S differs when executed later

    - name: Push Docker image to Docker Hub
      run: |
        docker tag todo-app:latest ${ secrets.DOCKER_USERNAME }/todo-app:latest
        docker push ${ secrets.DOCKER_USERNAME }todo-app:latest